# docker-compose.yml
version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - dev_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: axis
      POSTGRES_PASSWORD: secret

volumes:
    dev_pg_data:
        external: true
